### ISSUE TITLE
A quick question

### ISSUE THREAD

**Issue by perfectdeveloper53** [jwuestef/TimeStation#1]
Hi @jwuestef 
Thanks for your repository.

I'd like to know if this repository has most of functions from Timestation.
If yes, I want to discuss with you about a project.

Thanks

**Comment by jwuestef** [comment]
Hi @perfectdeveloper53, this was a project I used to learn and practice C#. If I recall, it might have some of the basic functionality, but it's definitely not a "real" project, and it's definitely not equivalent to the real "Timestation" product. I wouldn't recommend using it - this was meant as a learning project and not intended to actually be used.

By all means, you have my permission to clone/download/use to your heart's content, but I wouldn't recommend it. You'd be better off starting from scratch. While I appreciate the offer of a potential project, I've got a number of things that I'm already juggling at the moment.
